yelynn1/tictactoe

CODE OF CONDUCT.md
CONTRIBUTING GUIDE.md
README.md

Fixes #2 
* Added necessary contents to `README.md`. 
* Additionally I have created a `CONTRIBUTING.md` to keep it as a separate file.
* Also created the `CODE OF CONDUCT.md`

doc:Updated README.md and contribution files

---

style.css

Changes in border of style container

changes in border of style container

---

app.js

randomize start

---

CONTRIBUTING GUIDE.md
contributors.html

contributors file added

---

contributors.html
index.html
style.css

Added a Navigation bar on top and added link to contributions page and Game and About us page.

Added Nav bar link to Game and Contributions, About Page

---

app.js
contributors.css
contributors.html

- Added contributors 
- Removed redundant logs

Add contributors

---

contributors.css

Added corresponding css file for contributors.

Add contributor css

---

contributors.html
contributors.js

Used github API to create dynamic table for contributors.

contributors functionality done using github API

---

app.js
index.html
style.css

Interactive Scoreboard
----------------------------
Added new scoreboard which reflects coloring-based scoring.
1.  Win  <----->  Green
2.  Lost  <----->  Red
3.  Draw  <------>  Yellow

Interactive Scoreboard

---

style.css

This adds a new look to the dark made, and makes it more beautiful

Make the background color navy blue in dark  mode

---

app.js

The current version of the project did not seem to have a functioning scoreboard, so I added a bit of JS to update computer and player scores accordingly after wins, losses, and draws.

Adding scoreboard functionality

---

app.js
index.html
style.css

added a choose difficulty feature with 3 levels: easy, normal, and hard
easy mode takes the worst move returned by minimax() in descending order 
hard mode takes the best move returned by minimax() in descending order
normal mode takes the easy move 40% of the time & the hard move 60% of the time

Issue #12 - Add Choose Difficulty Feature

---

main.css
mainmenu.html

- Created a main page 
- Changed the style 
Suggestions for next steps:
These are some of the next steps i have on my mind. I would like to have your feedback about it and of course the permission to go for it. If there is someone else interested in helping with this, please feel free to!

Main Page Added / Style Changes

---

about.html
index.html
style.css

**Hello** @yelynn1 
- I fixed issue #41 and I improved the appearance of the About Page on the website. If you have any questions/concerns feel free to let me know via email: alanblandon@csu.fullerton.edu
- Before Update:
- After Update:

Fixed Issue #41 including an improvement on the appearance of the About Page

---

index.html
style.css

First I got rid of the greenish box in the headings which made them look a bit weird and the light/dark mode button is more user friendly with text that tells you exactly what mode the website will switch into
Secondly the dark mode was a bit harsh on the eyes with pure black. I lighted it to a dark grey and made it so it affected more of the site. Hopefully you like the color pallete! #33

Updated dark mode more holistically and toggle for Light and Dark

---

app.js
index.html
style.css

adding a new feature : a button to mute sounds at the end of the game

---

README.md

In readme.md
<a href="https://github.com/yelynn1/tictactoe/issues/98" target="_blank">Bug_98</a>
***Bug***
there is one  command missing before opening the index.html file.
in order to enhance readability can I work on this.
***Added***
```
cd tictactoe
```

added change directory command

---

app.js
index.html
index.mjs
style.css

- Adds an offline Two Player support to play with friends apart from the already existing Single Player(Vs Computer) Mode
- Updates UI  to show which Player has to make the current move

Add 2 Player support

---

app.js
index.html

**Pull Request Description:**
This pull request adds a new feature to the tic-tac-toe game: an undo button. Players can now undo their last move with a single click on the "Undo" button. This feature enhances the user experience and allows for more flexible gameplay.
**Changes Made:**
- Added a new variable `lastMove` to keep track of the last game board state.
- Modified the `addPlayerMove` function to store the current game board state in `lastMove` before each player move.
- Implemented the `undoLastMove` function, which reverts the game board to the previous state stored in `lastMove` when the "Undo" button is clicked.
- Updated the game initialization process to include the `lastMove` variable.
**How to Test:**
1. Start a new game or continue an existing one.
2. Make a move on the …

Added the Undo Move Button

---

CONTRIBUTING.md
app.js
index.html

Created two buttons so that player can choose which would go first when reset.

Reset Board button doesn't reset the table everytime (wierd and glitchy). #45
